using LanguageCore.Runtime;

namespace LanguageCore.ASM;

[ExcludeFromCodeCoverage]
public class AssemblyCode
{
    const string EntryPointSymbol = "_start";

    public static readonly ImmutableArray<string> ReservedWords = ImmutableArray.Create(
        "$",
        "DF",
        "GROUP",
        "ORG",
        "*",
        "DGROUP",
        "GT",
        "%OUT",
        "+",
        "DOSSEG",
        "HIGH",
        "PAGE",
        "_",
        "DQ",
        "IF",
        "PARA",
        ".",
        "DS",
        "IF1",
        "PROC",
        "/",
        "DT",
        "IF2",
        "PTR",
        "=",
        "DUP",
        "IFB",
        "PUBLIC",
        "?",
        "DW",
        "IFDEF",
        "PURGE",
        "[  ]",
        "DWORD",
        "IFGIF",
        "QWORD",
        ".186",
        "ELSE",
        "IFDE",
        ".RADIX",
        ".286",
        "END",
        "IFIDN",
        "RECORD",
        ".286P",
        "ENDIF",
        "IFNB",
        "REPT",
        ".287",
        "ENDM",
        "IFNDEF",
        ".SALL",
        ".386",
        "ENDP",
        "INCLUDE",
        "SEG",
        ".386P",
        "ENDS",
        "INCLUDELIB",
        "SEGMENT",
        ".387",
        "EQ",
        "IRP",
        ".SEQ",
        ".8086",
        "EQU",
        "IRPC",
        ".SFCOND",
        ".8087",
        ".ERR",
        "LABEL",
        "SHL",
        "ALIGN",
        ".ERR1",
        ".LALL",
        "SHORT",
        ".ALPHA",
        ".ERR2",
        "LARGE",
        "SHR",
        "AND",
        ".ERRB",
        "LE",
        "SIZE",
        "ASSUME",
        ".ERRDEF",
        "LENGTH",
        "SMALL",
        "AT",
        ".ERRDIF",
        ".LFCOND",
        "STACK",
        "BYTE",
        ".ERRE",
        ".LIST",
        "@STACK",
        ".CODE",
        ".ERRIDN",
        "LOCAL",
        ".STACK",
        "@CODE",
        ".ERRNB",
        "LOW",
        "STRUC",
        "@CODESIZE",
        ".ERRNDEF",
        "LT",
        "SUBTTL",
        "COMM",
        ".ERRNZ",
        "MACRO",
        "TBYTE",
        "COMMENT",
        "EVEN",
        "MASK",
        ".TFCOND",
        ".CONST",
        "EXITM",
        "MEDIUM",
        "THIS",
        ".CREF",
        "EXTRN",
        "MOD",
        "TITLE",
        "@CURSEG",
        "FAR",
        ".MODEL",
        "TYPE",
        "@DATA",
        "@FARDATA",
        "NAME",
        ".TYPE",
        ".DATA",
        ".FARDATA",
        "NE",
        "WIDTH",
        "@DATA?",
        "@FARDATA?",
        "NEAR",
        "WORD",
        ".DATA?",
        ".FARDATA?",
        "NOT",
        "@WORDSIZE",
                    "@DATASIZE",
        "@FILENAME",
        "NOTHING",
        ".XALL",
        "DB",
        "FWORD",
        "OFFSET",
        ".XCREP",
        "DD",
        "GE",
        "OR",
        ".XLIST",
        "XOR"
    );
    public const string ValidIdentifierCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

    public readonly TextSectionBuilder CodeBuilder;
    public readonly DataSectionBuilder DataBuilder;

    public AssemblyCode()
    {
        CodeBuilder = new TextSectionBuilder()
        {
            Indent = SectionBuilder.IndentIncrement,
        };
        DataBuilder = new DataSectionBuilder()
        {
            Indent = SectionBuilder.IndentIncrement,
        };
    }

    public static string GenerateLabel(string? prefix, int length, Func<string, bool>? isValidCallback)
    {
        StringBuilder result = new(prefix, length + (prefix?.Length ?? 0));

        int endlessSafe = 128;
        while (result.Length < length)
        {
            char newChar = ValidIdentifierCharacters[System.Random.Shared.Next(0, ValidIdentifierCharacters.Length)];
            while (AssemblyCode.IsReserved(result.ToString() + newChar) ||
                   isValidCallback == null ||
                   isValidCallback.Invoke(result.ToString() + newChar))
            {
                newChar = ValidIdentifierCharacters[System.Random.Shared.Next(0, ValidIdentifierCharacters.Length)];
                if (endlessSafe-- < 0) throw new EndlessLoopException();
            }
            result.Append(newChar);
        }

        return result.ToString();
    }

    public static bool IsReserved(string word)
    {
        for (int i = 0; i < ReservedWords.Length; i++)
        {
            if (string.Equals(ReservedWords[i], word, StringComparison.OrdinalIgnoreCase))
            { return true; }
        }
        return false;
    }

    public string Make(BitWidth bits)
    {
        StringBuilder builder = new();

        builder.AppendLine(";");
        builder.AppendLine("; WARNING: Generated by BB's compiler!");
        builder.AppendLine(";");
        builder.AppendLine();

        switch (bits)
        {
            case BitWidth._8:
                throw new NotImplementedException($"8 bit mode aint supported");
            case BitWidth._16:
                builder.AppendLine("[BITS 16]");
                // builder.AppendLine("ORG 100h");
                break;
            case BitWidth._32:
                builder.AppendLine("[BITS 32]");
                break;
            case BitWidth._64:
                builder.AppendLine("[BITS 64]");
                break;
        }

        if (CodeBuilder.Imports.Count > 0)
        {
            builder.AppendLine(";");
            builder.AppendLine("; External functions");
            builder.AppendLine(";");
            foreach (string import in CodeBuilder.Imports)
            {
                builder.AppendLine($"extern {import}");
            }
            builder.AppendLine();
        }

        if (bits != BitWidth._16)
        {
            builder.AppendLine(";");
            builder.AppendLine("; Global functions");
            builder.AppendLine(";");
            builder.AppendLine($"global {EntryPointSymbol}");
            builder.AppendLine();
        }

        builder.AppendLine(";");
        builder.AppendLine("; Code Section");
        builder.AppendLine(";");
        if (bits != BitWidth._16)
        { builder.AppendLine("section .text"); }
        builder.AppendLine();
        builder.AppendLine($"{EntryPointSymbol}:");

        builder.Append(CodeBuilder.Builder);
        builder.AppendLine();

        if (DataBuilder.Builder.Length > 0)
        {
            builder.AppendLine(";");
            builder.AppendLine("; Data Section");
            builder.AppendLine(";");
            builder.AppendLine("section .rodata");
            builder.Append(DataBuilder.Builder);
            builder.AppendLine();
        }

        return builder.ToString();
    }
}
