[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0301:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0303:Simplify collection initialization")]
[assembly: SuppressMessage("Roslynator", "RCS1138:Add summary to documentation comment")]
[assembly: SuppressMessage("Roslynator", "RCS1139:Add summary element to documentation comment")]
[assembly: SuppressMessage("Roslynator", "RCS1194:Implement exception constructors")]
[assembly: SuppressMessage("Roslynator", "RCS1214:Unnecessary interpolated string")]
[assembly: SuppressMessage("Roslynator", "RCS1073:Convert 'if' to 'return' statement")]
[assembly: SuppressMessage("Roslynator", "RCS1163:Unused parameter")]
[assembly: SuppressMessage("Roslynator", "RCS1146:Use conditional access")]
[assembly: SuppressMessage("Roslynator", "RCS1218:Simplify code branching")]
[assembly: SuppressMessage("Roslynator", "RCS1173:Use coalesce expression instead of 'if'")]
[assembly: SuppressMessage("Roslynator", "RCS1256:Invalid argument null check")]
[assembly: SuppressMessage("Roslynator", "RCS1075:Avoid empty catch clause that catches System.Exception")]
