using System.Runtime.Versioning;

namespace LanguageCore.Tests;

[Ignore]
[SupportedOSPlatform("linux")]
[TestClass, TestCategory("Asm"), TestCategory("FileTest")]
public class AsmFileTests
{
    const int Timeout = 5 * 1000;

    [TestMethod, Timeout(Timeout)] public void Test001() => TestList.GetTest(01).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test002() => TestList.GetTest(02).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test003() => TestList.GetTest(03).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test004() => TestList.GetTest(04).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test005() => TestList.GetTest(05).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test006() => TestList.GetTest(06).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test007() => TestList.GetTest(07).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test008() => TestList.GetTest(08).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test009() => TestList.GetTest(09).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test010() => TestList.GetTest(10).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test011() => TestList.GetTest(11).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test012() => TestList.GetTest(12).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test013() => TestList.GetTest(13).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test014() => TestList.GetTest(14).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test015() => TestList.GetTest(15).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test016() => TestList.GetTest(16).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test017() => TestList.GetTest(17).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test018() => TestList.GetTest(18).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test019() => TestList.GetTest(19).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test020() => TestList.GetTest(20).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test021() => TestList.GetTest(21).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test022() => TestList.GetTest(22).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test023() => TestList.GetTest(23).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test024() => TestList.GetTest(24).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test025() => TestList.GetTest(25).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test026() => TestList.GetTest(26).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test027() => TestList.GetTest(27).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test028() => TestList.GetTest(28).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test029() => TestList.GetTest(29).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test030() => TestList.GetTest(30).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test031() => TestList.GetTest(31).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test032() => TestList.GetTest(32).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test033() => TestList.GetTest(33).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test034() => TestList.GetTest(34).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test035() => TestList.GetTest(35).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test036() => TestList.GetTest(36).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test037() => TestList.GetTest(37).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test038() => TestList.GetTest(38).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test039() => TestList.GetTest(39).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test040() => TestList.GetTest(40).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test041() => TestList.GetTest(41).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test042() => TestList.GetTest(42).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test043() => TestList.GetTest(43).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test044() => TestList.GetTest(44).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test045() => TestList.GetTest(45).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore(":(")] public void Test046() => TestList.GetTest(46).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test047() => TestList.GetTest(47).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test048() => TestList.GetTest(48).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test049() => TestList.GetTest(49).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test050() => TestList.GetTest(50).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test051() => TestList.GetTest(51).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test052() => TestList.GetTest(52).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test053() => TestList.GetTest(53).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test054() => TestList.GetTest(54).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test055() => TestList.GetTest(55).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test056() => TestList.GetTest(56).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test057() => TestList.GetTest(57).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test058() => TestList.GetTest(58).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test059() => TestList.GetTest(59).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test060() => TestList.GetTest(60).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test061() => TestList.GetTest(61).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test062() => TestList.GetTest(62).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test063() => TestList.GetTest(63).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test064() => TestList.GetTest(64).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test065() => TestList.GetTest(65).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test066() => TestList.GetTest(66).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test067() => TestList.GetTest(67).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test068() => TestList.GetTest(68).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test069() => TestList.GetTest(69).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test070() => TestList.GetTest(70).DoAssembly();
    [TestMethod, Timeout(Timeout)] public void Test071() => TestList.GetTest(71).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test072() => TestList.GetTest(72).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test073() => TestList.GetTest(73).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test074() => TestList.GetTest(74).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test075() => TestList.GetTest(75).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test076() => TestList.GetTest(76).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test077() => TestList.GetTest(77).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test078() => TestList.GetTest(78).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test079() => TestList.GetTest(79).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test080() => TestList.GetTest(80).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test081() => TestList.GetTest(81).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test082() => TestList.GetTest(82).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test083() => TestList.GetTest(83).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test084() => TestList.GetTest(84).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test085() => TestList.GetTest(85).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test086() => TestList.GetTest(86).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test087() => TestList.GetTest(87).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test088() => TestList.GetTest(88).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test089() => TestList.GetTest(89).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test090() => TestList.GetTest(90).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test091() => TestList.GetTest(91).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test092() => TestList.GetTest(92).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test093() => TestList.GetTest(93).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test094() => TestList.GetTest(94).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test095() => TestList.GetTest(95).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test096() => TestList.GetTest(96).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test097() => TestList.GetTest(97).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test098() => TestList.GetTest(98).DoAssembly();
    [TestMethod, Timeout(Timeout), Ignore("Not implemented")] public void Test099() => TestList.GetTest(99).DoAssembly();
}
