using LanguageCore.Runtime;

namespace LanguageCore.Tests;

[TestClass, TestCategory("Main"), TestCategory("Generic")]
public class MainTests
{
    const int Timeout = 20 * 1000;

    [TestMethod, Timeout(Timeout)] public void Test001() => TestList.GetTest(01).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test002() => TestList.GetTest(02).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test003() => TestList.GetTest(03).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test004() => TestList.GetTest(04).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test005() => TestList.GetTest(05).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test006() => TestList.GetTest(06).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test007() => TestList.GetTest(07).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test008() => TestList.GetTest(08).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test009() => TestList.GetTest(09).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test010() => TestList.GetTest(10).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test011() => TestList.GetTest(11).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test012() => TestList.GetTest(12).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test013() => TestList.GetTest(13).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test014() => TestList.GetTest(14).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test015() => TestList.GetTest(15).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test016() => TestList.GetTest(16).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test017() => TestList.GetTest(17).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test018() => TestList.GetTest(18).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test019() => TestList.GetTest(19).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test020() => TestList.GetTest(20).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test021() => TestList.GetTest(21).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test022() => TestList.GetTest(22).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test023() => TestList.GetTest(23).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test024() => TestList.GetTest(24).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test025() => TestList.GetTest(25).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test026() => TestList.GetTest(26).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test027() => TestList.GetTest(27).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test028() => TestList.GetTest(28).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test029() => TestList.GetTest(29).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test030() => TestList.GetTest(30).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test031() => TestList.GetTest(31).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test032() => TestList.GetTest(32).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test033() => TestList.GetTest(33).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test034() => TestList.GetTest(34).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test035() => TestList.GetTest(35).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test036() => TestList.GetTest(36).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test037() => TestList.GetTest(37).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test038() => TestList.GetTest(38).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test039() => TestList.GetTest(39).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test040() => TestList.GetTest(40).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test041() => TestList.GetTest(41).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test042() => TestList.GetTest(42).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test043() => TestList.GetTest(43).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test044() => TestList.GetTest(44).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test045() => TestList.GetTest(45).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test046() => TestList.GetTest(46).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test047() => TestList.GetTest(47).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test048() => TestList.GetTest(48).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test049() => TestList.GetTest(49).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test050() => TestList.GetTest(50).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test051() => TestList.GetTest(51).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test052() => TestList.GetTest(52).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test053() => TestList.GetTest(53).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test054() => TestList.GetTest(54).DoMain();
    [TestMethod, Timeout(Timeout)]
    public void Test055() => TestList.GetTest(55).DoMain(externalFunctionAdder: static (externalFunctions) =>
    {
        externalFunctions.AddExternalFunction(ExternalFunctionSync.Create(externalFunctions.GenerateId(), "test", static (int a, int b, int c, int d) =>
        {
            Assert.AreEqual(a, 1, "parameter 0");
            Assert.AreEqual(b, 2, "parameter 1");
            Assert.AreEqual(c, 3, "parameter 2");
            Assert.AreEqual(d, 4, "parameter 3");
        }));
    });
    [TestMethod, Timeout(Timeout)] public void Test056() => TestList.GetTest(56).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test057() => TestList.GetTest(57).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test058() => TestList.GetTest(58).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test059() => TestList.GetTest(59).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test060() => TestList.GetTest(60).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test061() => TestList.GetTest(61).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test062() => TestList.GetTest(62).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test063() => TestList.GetTest(63).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test064() => TestList.GetTest(64).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test065() => TestList.GetTest(65).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test066() => TestList.GetTest(66).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test067() => TestList.GetTest(67).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test068() => TestList.GetTest(68).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test069() => TestList.GetTest(69).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test070() => TestList.GetTest(70).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test071() => TestList.GetTest(71).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test072() => TestList.GetTest(72).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test073() => TestList.GetTest(73).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test074() => TestList.GetTest(74).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test075() => TestList.GetTest(75).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test076() => TestList.GetTest(76).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test077() => TestList.GetTest(77).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test078() => TestList.GetTest(78).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test079() => TestList.GetTest(79).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test080() => TestList.GetTest(80).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test081() => TestList.GetTest(81).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test082() => TestList.GetTest(82).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test083() => TestList.GetTest(83).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test084() => TestList.GetTest(84).DoMain(); // NOTE: Expected output modified because the square root algorithm is not accurate enough
    [TestMethod, Timeout(Timeout)] public void Test085() => TestList.GetTest(85).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test086() => TestList.GetTest(86).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test087() => TestList.GetTest(87).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test088() => TestList.GetTest(88).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test089() => TestList.GetTest(89).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test090() => TestList.GetTest(90).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test091() => TestList.GetTest(91).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test092() => TestList.GetTest(92).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test093() => TestList.GetTest(93).DoMain();
    [TestMethod, Timeout(Timeout), Ignore("No (tasks)")] public void Test094() => TestList.GetTest(94).DoMain();
    [TestMethod, Timeout(Timeout), Ignore("Dumbass")] public void Test095() => TestList.GetTest(95).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test096() => TestList.GetTest(96).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test097() => TestList.GetTest(97).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test098() => TestList.GetTest(98).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test099() => TestList.GetTest(99).DoMain();
    [TestMethod, Timeout(Timeout), Ignore("No (exposed func)")] public void Test100() => TestList.GetTest(100).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test101() => TestList.GetTest(101).DoMain();
    [TestMethod, Timeout(Timeout), Ignore("No")] public void Test102() => TestList.GetTest(102).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test103() => TestList.GetTest(103).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test104() => TestList.GetTest(104).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test105() => TestList.GetTest(105).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test106() => TestList.GetTest(106).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test107() => TestList.GetTest(107).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test108() => TestList.GetTest(108).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test109() => TestList.GetTest(109).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test110() => TestList.GetTest(110).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test111() => TestList.GetTest(111).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test112() => TestList.GetTest(112).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test113() => TestList.GetTest(113).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test114() => TestList.GetTest(114).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test115() => TestList.GetTest(115).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test116() => TestList.GetTest(116).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test117() => TestList.GetTest(117).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test118() => TestList.GetTest(118).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test119() => TestList.GetTest(119).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test120() => TestList.GetTest(120).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test121() => TestList.GetTest(121).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test122() => TestList.GetTest(122).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test123() => TestList.GetTest(123).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test124() => TestList.GetTest(124).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test125() => TestList.GetTest(125).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test126() => TestList.GetTest(126).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test127() => TestList.GetTest(127).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test128() => TestList.GetTest(128).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test129() => TestList.GetTest(129).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test130() => TestList.GetTest(130).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test131() => TestList.GetTest(131).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test132() => TestList.GetTest(132).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test133() => TestList.GetTest(133).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test134() => TestList.GetTest(134).DoMain();
    [TestMethod, Timeout(Timeout)] public void Test135() => TestList.GetTest(135).DoMain();
}
