namespace LanguageCore.Runtime;

public static class OpcodeExtensions
{
    public static int ParameterCount(this Opcode opcode) => opcode switch
    {
        Opcode.NOP => 0,
        Opcode.Push => 1,
        Opcode.Pop8 => 0,
        Opcode.Pop16 => 0,
        Opcode.Pop32 => 0,
        Opcode.PopTo8 => 1,
        Opcode.PopTo16 => 1,
        Opcode.PopTo32 => 1,
        Opcode.PopTo64 => 1,
        Opcode.Exit => 0,
        Opcode.Call => 1,
        Opcode.Return => 0,
        Opcode.JumpIfEqual => 1,
        Opcode.JumpIfNotEqual => 1,
        Opcode.JumpIfGreater => 1,
        Opcode.JumpIfGreaterOrEqual => 1,
        Opcode.JumpIfLess => 1,
        Opcode.JumpIfLessOrEqual => 1,
        Opcode.Jump => 1,
        Opcode.CallExternal => 1,
        Opcode.Crash => 1,
        Opcode.Compare => 2,
        Opcode.CompareF => 2,
        Opcode.LogicOR => 2,
        Opcode.LogicAND => 2,
        Opcode.BitsAND => 2,
        Opcode.BitsOR => 2,
        Opcode.BitsXOR => 2,
        Opcode.BitsNOT => 1,
        Opcode.BitsShiftLeft => 2,
        Opcode.BitsShiftRight => 2,
        Opcode.MathAdd => 2,
        Opcode.MathSub => 2,
        Opcode.MathMult => 2,
        Opcode.MathDiv => 2,
        Opcode.MathMod => 2,
        Opcode.FMathAdd => 2,
        Opcode.FMathSub => 2,
        Opcode.FMathMult => 2,
        Opcode.FMathDiv => 2,
        Opcode.FMathMod => 2,
        Opcode.UMathAdd => 2,
        Opcode.UMathSub => 2,
        Opcode.UMathMult => 2,
        Opcode.UMathDiv => 2,
        Opcode.UMathMod => 2,
        Opcode.Move => 2,
        Opcode.FTo => 1,
        Opcode.FFrom => 1,
        _ => throw new UnreachableException(),
    };
}
