name: .NET Core Desktop

on:
  workflow_dispatch:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:

  build:
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      # shell: pwsh
      run: |
        echo Bruh >release.txt  
      # .\build.ps1

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        path: .\Published\JIT

    - name: Create Tag
      uses: EndBug/latest-tag@latest
      with:
        # You can change the name of the tag or branch with this input.
        # Default: 'latest'
        ref: latest

        # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
        # Default: ''
        # description: Description for the tag

        # Force-update a branch instead of using a tag.
        # Default: false
        force-branch: true

        # Directory to use when executing git commands
        # Default: '${{ github.workspace }}'
        # git-directory: 'path/to/repo/dir'

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release.txt
        #files: ./Published/JIT.zip
        #tag_name: latest

    - name: Cleanup
      shell: pwsh
      run: |
        .\cleanup.ps1
