name: .NET Core Desktop

on:
  workflow_dispatch:

jobs:

  build:
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Prepare build
      shell: pwsh
      run: |
        mkdir BuildJob

    - name: Cloning repositories
      shell: pwsh
      working-directory: ./BuildJob
      run: |
        ..\clone-repos.ps1

    - name: Building
      shell: pwsh
      working-directory: ./BuildJob
      run: |
        ..\build.ps1

    - name: Cleaning up the projects
      shell: pwsh
      working-directory: ./BuildJob
      run: |
        ..\cleanup-projects.ps1

    - name: Compressing
      shell: pwsh
      working-directory: ./BuildJob
      run: |
        ..\compress.ps1

    - name: Cleaning up
      shell: pwsh
      working-directory: ./BuildJob
      run: |
        if (Test-Path -Path ./Published) { Remove-Item -LiteralPath ./Published -Force -Recurse }

#    - name: Upload artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        path: .\Published\JIT

    - name: Create tag
      uses: EndBug/latest-tag@latest
      with:
        # Default: 'latest'
        ref: latest

        # Default: ''
        # description: Description for the tag

        # Default: false
        force-branch: true

        # Default: '${{ github.workspace }}'
        # git-directory: 'path/to/repo/dir'

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./BuildJob/Windows_x64_RuntimeIndependent.zip
          ./BuildJob/Windows_x64_RuntimeDependent.zip
          ./BuildJob/Windows_x64_AOT.zip
        tag_name: latest
        name: The Release
        fail_on_unmatched_files: true
